// Auto-generated table of contents
// Generated on 2025-10-10T09:50:25.795Z

export const questdbTocList = {
  "functions": [
    "Aggregate functions",
    "Aggregate functions - approx_count_distinct",
    "Aggregate functions - approx_median",
    "Aggregate functions - approx_percentile",
    "Aggregate functions - avg",
    "Aggregate functions - corr",
    "Aggregate functions - count",
    "Aggregate functions - count_distinct",
    "Aggregate functions - covar_pop",
    "Aggregate functions - covar_samp",
    "Aggregate functions - first/last",
    "Aggregate functions - first_not_null",
    "Aggregate functions - haversine_dist_deg",
    "Aggregate functions - ksum",
    "Aggregate functions - last_not_null",
    "Aggregate functions - max",
    "Aggregate functions - min",
    "Aggregate functions - nsum",
    "Aggregate functions - stddev / stddev_samp",
    "Aggregate functions - stddev_pop",
    "Aggregate functions - string_agg",
    "Aggregate functions - string_distinct_agg",
    "Aggregate functions - sum",
    "Aggregate functions - var_pop",
    "Aggregate functions - variance / var_samp",
    "Array functions",
    "Array functions - array_avg",
    "Array functions - array_count",
    "Array functions - array_cum_sum",
    "Array functions - array_max",
    "Array functions - array_min",
    "Array functions - array_position",
    "Array functions - array_stddev",
    "Array functions - array_stddev_pop",
    "Array functions - array_stddev_samp",
    "Array functions - array_sum",
    "Array functions - dim_length",
    "Array functions - dot_product",
    "Array functions - flatten",
    "Array functions - insertion_point",
    "Array functions - matmul",
    "Array functions - shift",
    "Array functions - transpose",
    "Binary functions",
    "Binary functions - See also",
    "Binary functions - base64",
    "Boolean functions",
    "Boolean functions - SELECT boolean expressions",
    "Boolean functions - isOrdered",
    "Conditional functions",
    "Conditional functions - case",
    "Conditional functions - coalesce",
    "Conditional functions - nullif",
    "Finance functions",
    "Finance functions - l2price",
    "Finance functions - mid",
    "Finance functions - regr_intercept",
    "Finance functions - regr_slope",
    "Finance functions - spread_bps",
    "Finance functions - vwap",
    "Finance functions - wmid",
    "Geospatial functions",
    "Geospatial functions - make_geohash",
    "Geospatial functions - rnd_geohash",
    "Hash Functions",
    "Hash Functions - Function reference",
    "Hash Functions - Notes and restrictions",
    "Hash Functions - Supported functions",
    "JSON functions",
    "JSON functions - json_extract",
    "Meta functions",
    "Meta functions - build",
    "Meta functions - current database, schema, or user",
    "Meta functions - flush_query_cache()",
    "Meta functions - functions",
    "Meta functions - hydrate_table_metadata('table1', 'table2' ...)",
    "Meta functions - materialized_views",
    "Meta functions - memory_metrics",
    "Meta functions - query_activity",
    "Meta functions - reader_pool",
    "Meta functions - reload_config()",
    "Meta functions - table_columns",
    "Meta functions - table_partitions",
    "Meta functions - table_storage",
    "Meta functions - tables",
    "Meta functions - version/pg_catalog.version",
    "Meta functions - wal_tables",
    "Meta functions - writer_pool",
    "Numeric functions",
    "Numeric functions - abs",
    "Numeric functions - ceil / ceiling",
    "Numeric functions - exp",
    "Numeric functions - floor",
    "Numeric functions - greatest",
    "Numeric functions - least",
    "Numeric functions - ln",
    "Numeric functions - log",
    "Numeric functions - power",
    "Numeric functions - round",
    "Numeric functions - round_down",
    "Numeric functions - round_half_even",
    "Numeric functions - round_up",
    "Numeric functions - sign",
    "Numeric functions - size_pretty",
    "Numeric functions - sqrt",
    "Parquet functions",
    "Parquet functions - read_parquet",
    "Pattern matching operators",
    "Pattern matching operators - LIKE/ILIKE",
    "Pattern matching operators - regexp_replace",
    "Pattern matching operators - ~ (match) and !~ (does not match)",
    "Random value generator",
    "Random value generator - Generating sequences",
    "Random value generator - Usage",
    "Random value generator - rnd_bin",
    "Random value generator - rnd_boolean",
    "Random value generator - rnd_byte",
    "Random value generator - rnd_char",
    "Random value generator - rnd_date()",
    "Random value generator - rnd_double",
    "Random value generator - rnd_double_array()",
    "Random value generator - rnd_float",
    "Random value generator - rnd_int",
    "Random value generator - rnd_ipv4()",
    "Random value generator - rnd_ipv4(string, int)",
    "Random value generator - rnd_long",
    "Random value generator - rnd_long256",
    "Random value generator - rnd_short",
    "Random value generator - rnd_str",
    "Random value generator - rnd_symbol",
    "Random value generator - rnd_timestamp()",
    "Random value generator - rnd_uuid4",
    "Random value generator - rnd_varchar",
    "Row generator",
    "Row generator - generate_series",
    "Row generator - long_sequence",
    "Text functions",
    "Text functions - concat",
    "Text functions - left",
    "Text functions - length",
    "Text functions - lpad",
    "Text functions - ltrim",
    "Text functions - quote_ident",
    "Text functions - replace",
    "Text functions - right",
    "Text functions - rtrim",
    "Text functions - split_part",
    "Text functions - starts_with",
    "Text functions - string_agg",
    "Text functions - strpos / position",
    "Text functions - substring",
    "Text functions - to_lowercase / lower",
    "Text functions - to_uppercase / upper",
    "Text functions - trim",
    "Timestamp function",
    "Timestamp function - Optimization with WHERE clauses",
    "Timestamp function - Syntax",
    "Timestamp generator",
    "Timestamp generator - generate_series",
    "Timestamp generator - timestamp_sequence",
    "Timestamp, date and time functions",
    "Timestamp, date and time functions - Timestamp format",
    "Timestamp, date and time functions - Timestamp to Date conversion",
    "Timestamp, date and time functions - date_trunc",
    "Timestamp, date and time functions - dateadd",
    "Timestamp, date and time functions - datediff",
    "Timestamp, date and time functions - day",
    "Timestamp, date and time functions - day_of_week",
    "Timestamp, date and time functions - day_of_week_sunday_first",
    "Timestamp, date and time functions - days_in_month",
    "Timestamp, date and time functions - extract",
    "Timestamp, date and time functions - hour",
    "Timestamp, date and time functions - interval",
    "Timestamp, date and time functions - interval_end",
    "Timestamp, date and time functions - interval_start",
    "Timestamp, date and time functions - is_leap_year",
    "Timestamp, date and time functions - micros",
    "Timestamp, date and time functions - millis",
    "Timestamp, date and time functions - minute",
    "Timestamp, date and time functions - month",
    "Timestamp, date and time functions - nanos",
    "Timestamp, date and time functions - now",
    "Timestamp, date and time functions - pg_postmaster_start_time",
    "Timestamp, date and time functions - second",
    "Timestamp, date and time functions - sysdate",
    "Timestamp, date and time functions - systimestamp",
    "Timestamp, date and time functions - systimestamp_ns",
    "Timestamp, date and time functions - timestamp_ceil",
    "Timestamp, date and time functions - timestamp_floor",
    "Timestamp, date and time functions - timestamp_shuffle",
    "Timestamp, date and time functions - to_date",
    "Timestamp, date and time functions - to_str",
    "Timestamp, date and time functions - to_timestamp",
    "Timestamp, date and time functions - to_timestamp_ns",
    "Timestamp, date and time functions - to_timezone",
    "Timestamp, date and time functions - to_utc",
    "Timestamp, date and time functions - today, tomorrow, yesterday",
    "Timestamp, date and time functions - today, tomorrow, yesterday with timezone",
    "Timestamp, date and time functions - week_of_year",
    "Timestamp, date and time functions - year",
    "Touch function",
    "Trigonometric functions",
    "Trigonometric functions - acos",
    "Trigonometric functions - asin",
    "Trigonometric functions - atan",
    "Trigonometric functions - atan2",
    "Trigonometric functions - cos",
    "Trigonometric functions - cot",
    "Trigonometric functions - degrees",
    "Trigonometric functions - pi",
    "Trigonometric functions - radians",
    "Trigonometric functions - sin",
    "Trigonometric functions - tan",
    "UUID functions",
    "UUID functions - to_uuid",
    "Window Functions",
    "Window Functions - Common window function examples",
    "Window Functions - avg()",
    "Window Functions - count()",
    "Window Functions - dense_rank()",
    "Window Functions - first_not_null_value()",
    "Window Functions - first_value()",
    "Window Functions - lag()",
    "Window Functions - last_value()",
    "Window Functions - lead()",
    "Window Functions - max()",
    "Window Functions - min()",
    "Window Functions - rank()",
    "Window Functions - row_number()",
    "Window Functions - sum()"
  ],
  "operators": [
    "Bitwise Operators",
    "Bitwise Operators - `&` AND",
    "Bitwise Operators - `^` XOR",
    "Bitwise Operators - `|` OR",
    "Bitwise Operators - `~` NOT",
    "Comparison Operators",
    "Comparison Operators - `<=` Lesser than or equal to",
    "Comparison Operators - `<>` or `!=` Not equals",
    "Comparison Operators - `<` Lesser than",
    "Comparison Operators - `=` Equals",
    "Comparison Operators - `>=` Greater than or equal to",
    "Comparison Operators - `>` Greater than",
    "Comparison Operators - `IN` (list)",
    "Comparison Operators - `IN` (value1, value2, ...)",
    "Date and Time Operators",
    "Date and Time Operators - `BETWEEN` value1 `AND` value2",
    "Date and Time Operators - `IN` (interval)",
    "Date and Time Operators - `IN` (timeRange)",
    "Date and Time Operators - `IN` (timeRangeWithModifier)",
    "IPv4 Operators",
    "IPv4 Operators - Return netmask - netmask(string)",
    "IPv4 Operators - `!=` Does not equal",
    "IPv4 Operators - `&` Bitwise AND",
    "IPv4 Operators - `+` Add offset to an IP address",
    "IPv4 Operators - `-` Difference between two IP addresses",
    "IPv4 Operators - `-` Subtract offset from IP address",
    "IPv4 Operators - `<<=` Left IP address contained by or equal",
    "IPv4 Operators - `<<=` Right IP address contained by or equal",
    "IPv4 Operators - `<<` Left strict IP address contained by",
    "IPv4 Operators - `<=` Less than or equal",
    "IPv4 Operators - `<` Less than",
    "IPv4 Operators - `=` Equals",
    "IPv4 Operators - `>=` Greater than or equal",
    "IPv4 Operators - `>>` Right strict IP address contained by",
    "IPv4 Operators - `>` Greater than",
    "IPv4 Operators - `|` Bitwise OR",
    "IPv4 Operators - `~` Bitwise NOT",
    "Logical Operators",
    "Logical Operators - `AND` Logical AND",
    "Logical Operators - `NOT` Logical NOT",
    "Logical Operators - `OR` Logical OR",
    "Misc Operators",
    "Misc Operators - `.` Prefix",
    "Misc Operators - `::` Cast",
    "Numeric Operators",
    "Numeric Operators - `%` Modulo",
    "Numeric Operators - `*` Multiply",
    "Numeric Operators - `+` Add",
    "Numeric Operators - `-` Negate",
    "Numeric Operators - `-` Subtract",
    "Numeric Operators - `/` Divide",
    "Operator Precedence Table",
    "Operator Precedence Table - Pre-8.0 notice",
    "Spatial Operators",
    "Text Operators",
    "Text Operators - `!~` Regex doesn't match",
    "Text Operators - `ILIKE`",
    "Text Operators - `LIKE`",
    "Text Operators - `||` Concat",
    "Text Operators - `~` Regex match"
  ],
  "sql": [
    "ADD USER reference",
    "ADD USER reference - Description",
    "ADD USER reference - Syntax",
    "ALTER MATERIALIZED VIEW ADD INDEX",
    "ALTER MATERIALIZED VIEW ADD INDEX - Syntax",
    "ALTER MATERIALIZED VIEW ALTER COLUMN DROP INDEX",
    "ALTER MATERIALIZED VIEW ALTER COLUMN DROP INDEX - Syntax",
    "ALTER MATERIALIZED VIEW RESUME WAL",
    "ALTER MATERIALIZED VIEW RESUME WAL - See also",
    "ALTER MATERIALIZED VIEW RESUME WAL - Syntax",
    "ALTER MATERIALIZED VIEW SET REFRESH",
    "ALTER MATERIALIZED VIEW SET REFRESH - Description",
    "ALTER MATERIALIZED VIEW SET REFRESH - Syntax",
    "ALTER MATERIALIZED VIEW SET REFRESH LIMIT",
    "ALTER MATERIALIZED VIEW SET REFRESH LIMIT - Description",
    "ALTER MATERIALIZED VIEW SET REFRESH LIMIT - Syntax",
    "ALTER MATERIALIZED VIEW SET TTL",
    "ALTER MATERIALIZED VIEW SET TTL - Description",
    "ALTER MATERIALIZED VIEW SET TTL - Syntax",
    "ALTER MATERIALIZED VIEW SYMBOL CAPACITY",
    "ALTER MATERIALIZED VIEW SYMBOL CAPACITY - Notes",
    "ALTER MATERIALIZED VIEW SYMBOL CAPACITY - Syntax",
    "ALTER SERVICE ACCOUNT reference",
    "ALTER SERVICE ACCOUNT reference - Description",
    "ALTER SERVICE ACCOUNT reference - Syntax",
    "ALTER TABLE ADD COLUMN",
    "ALTER TABLE ADD COLUMN - OWNED BY",
    "ALTER TABLE ADD COLUMN - Syntax",
    "ALTER TABLE ATTACH PARTITION",
    "ALTER TABLE ATTACH PARTITION - Description",
    "ALTER TABLE ATTACH PARTITION - Limitation",
    "ALTER TABLE ATTACH PARTITION - Syntax",
    "ALTER TABLE COLUMN ADD INDEX",
    "ALTER TABLE COLUMN ADD INDEX - Syntax",
    "ALTER TABLE COLUMN CACHE | NOCACHE",
    "ALTER TABLE COLUMN CACHE | NOCACHE - Syntax",
    "ALTER TABLE COLUMN DROP INDEX",
    "ALTER TABLE COLUMN DROP INDEX - Syntax",
    "ALTER TABLE COLUMN TYPE",
    "ALTER TABLE COLUMN TYPE - Available Conversions",
    "ALTER TABLE COLUMN TYPE - Supported Data Types",
    "ALTER TABLE COLUMN TYPE - Syntax",
    "ALTER TABLE COLUMN TYPE - Unsupported Conversions",
    "ALTER TABLE DEDUP DISABLE",
    "ALTER TABLE DEDUP DISABLE - Syntax",
    "ALTER TABLE DEDUP ENABLE",
    "ALTER TABLE DEDUP ENABLE - See also",
    "ALTER TABLE DEDUP ENABLE - Syntax",
    "ALTER TABLE DETACH PARTITION",
    "ALTER TABLE DETACH PARTITION - Limitation",
    "ALTER TABLE DETACH PARTITION - Syntax",
    "ALTER TABLE DROP COLUMN",
    "ALTER TABLE DROP COLUMN - Syntax",
    "ALTER TABLE DROP PARTITION",
    "ALTER TABLE DROP PARTITION - Drop partition by name",
    "ALTER TABLE DROP PARTITION - Drop partitions using boolean expression",
    "ALTER TABLE DROP PARTITION - Syntax",
    "ALTER TABLE RENAME COLUMN",
    "ALTER TABLE RENAME COLUMN - Syntax",
    "ALTER TABLE RESUME WAL",
    "ALTER TABLE RESUME WAL - Description",
    "ALTER TABLE RESUME WAL - Diagnosing corrupted WAL transactions",
    "ALTER TABLE RESUME WAL - Syntax",
    "ALTER TABLE SET PARAM",
    "ALTER TABLE SET PARAM - Syntax",
    "ALTER TABLE SET TTL",
    "ALTER TABLE SET TTL - Description",
    "ALTER TABLE SET TTL - Syntax",
    "ALTER TABLE SET TYPE",
    "ALTER TABLE SET TYPE - Description",
    "ALTER TABLE SET TYPE - Syntax",
    "ALTER TABLE SQUASH PARTITIONS",
    "ALTER TABLE SQUASH PARTITIONS - Syntax",
    "ALTER TABLE SYMBOL CAPACITY",
    "ALTER TABLE SYMBOL CAPACITY - Notes",
    "ALTER TABLE SYMBOL CAPACITY - Syntax",
    "ALTER USER reference",
    "ALTER USER reference - Description",
    "ALTER USER reference - Syntax",
    "ASOF JOIN keyword",
    "ASOF JOIN keyword - ASOF JOIN",
    "ASOF JOIN keyword - JOIN overview",
    "ASOF JOIN keyword - SPLICE JOIN",
    "ASSUME SERVICE ACCOUNT reference",
    "ASSUME SERVICE ACCOUNT reference - Syntax",
    "CANCEL QUERY",
    "CANCEL QUERY - Description",
    "CANCEL QUERY - Syntax",
    "CASE keyword",
    "CASE keyword - Description",
    "CASE keyword - Syntax",
    "CAST keyword",
    "CAST keyword - Alternate syntax",
    "CAST keyword - Explicit conversion",
    "CAST keyword - Implicit conversion",
    "CAST keyword - Syntax",
    "CHECKPOINT keyword",
    "CHECKPOINT keyword - CHECKPOINT examples",
    "CHECKPOINT keyword - CHECKPOINT overview",
    "CHECKPOINT keyword - CHECKPOINT syntax",
    "COPY keyword",
    "COPY keyword - Description",
    "COPY keyword - Options",
    "COPY keyword - Syntax",
    "CREATE GROUP reference",
    "CREATE GROUP reference - Description",
    "CREATE GROUP reference - Syntax",
    "CREATE MATERIALIZED VIEW",
    "CREATE MATERIALIZED VIEW - Alternative refresh strategies",
    "CREATE MATERIALIZED VIEW - Base table",
    "CREATE MATERIALIZED VIEW - Creating a view",
    "CREATE MATERIALIZED VIEW - IF NOT EXISTS",
    "CREATE MATERIALIZED VIEW - Initial refresh",
    "CREATE MATERIALIZED VIEW - Materialized view names",
    "CREATE MATERIALIZED VIEW - Metadata",
    "CREATE MATERIALIZED VIEW - OWNED BY (Enterprise)",
    "CREATE MATERIALIZED VIEW - Partitioning",
    "CREATE MATERIALIZED VIEW - Period materialized views",
    "CREATE MATERIALIZED VIEW - Query constraints",
    "CREATE MATERIALIZED VIEW - SYMBOL column capacity",
    "CREATE MATERIALIZED VIEW - Syntax",
    "CREATE MATERIALIZED VIEW - Time To Live (TTL)",
    "CREATE SERVICE ACCOUNT reference",
    "CREATE SERVICE ACCOUNT reference - Description",
    "CREATE SERVICE ACCOUNT reference - Syntax",
    "CREATE TABLE reference",
    "CREATE TABLE reference - CREATE TABLE AS",
    "CREATE TABLE reference - CREATE TABLE LIKE",
    "CREATE TABLE reference - Column indexes",
    "CREATE TABLE reference - Column name",
    "CREATE TABLE reference - Deduplication",
    "CREATE TABLE reference - Designated timestamp",
    "CREATE TABLE reference - IF NOT EXISTS",
    "CREATE TABLE reference - OWNED BY",
    "CREATE TABLE reference - Partitioning",
    "CREATE TABLE reference - Syntax",
    "CREATE TABLE reference - Table name",
    "CREATE TABLE reference - Table target volume",
    "CREATE TABLE reference - Time To Live (TTL)",
    "CREATE TABLE reference - Type definition",
    "CREATE TABLE reference - WITH table parameter",
    "CREATE TABLE reference - Write-Ahead Log (WAL) Settings",
    "CREATE USER reference",
    "CREATE USER reference - Conditional user creation",
    "CREATE USER reference - Description",
    "CREATE USER reference - Syntax",
    "DECLARE keyword",
    "DECLARE keyword - Limitations",
    "DECLARE keyword - Mechanics",
    "DECLARE keyword - Syntax",
    "DISTINCT keyword",
    "DISTINCT keyword - Syntax",
    "DROP GROUP reference",
    "DROP GROUP reference - Description",
    "DROP GROUP reference - Syntax",
    "DROP MATERIALIZED VIEW",
    "DROP MATERIALIZED VIEW - IF EXISTS",
    "DROP MATERIALIZED VIEW - See also",
    "DROP MATERIALIZED VIEW - Syntax",
    "DROP SERVICE ACCOUNT reference",
    "DROP SERVICE ACCOUNT reference - Description",
    "DROP SERVICE ACCOUNT reference - Syntax",
    "DROP TABLE keyword",
    "DROP TABLE keyword - Description",
    "DROP TABLE keyword - See also",
    "DROP TABLE keyword - Syntax",
    "DROP USER reference",
    "DROP USER reference - Description",
    "DROP USER reference - Syntax",
    "Data types",
    "Data types - IPv4",
    "Data types - Limitations for variable-sized types",
    "Data types - N-dimensional array",
    "Data types - TIMESTAMP and DATE considerations",
    "Data types - The UUID type",
    "Data types - Type nullability",
    "Data types - VARCHAR and STRING considerations",
    "EXIT SERVICE ACCOUNT reference",
    "EXIT SERVICE ACCOUNT reference - Syntax",
    "EXPLAIN keyword",
    "EXPLAIN keyword - Limitations:",
    "EXPLAIN keyword - See also",
    "EXPLAIN keyword - Syntax",
    "FILL keyword",
    "GRANT ASSUME SERVICE ACCOUNT reference",
    "GRANT ASSUME SERVICE ACCOUNT reference - Description",
    "GRANT ASSUME SERVICE ACCOUNT reference - Syntax",
    "GRANT reference",
    "GRANT reference - Description",
    "GRANT reference - Syntax",
    "GROUP BY keyword",
    "GROUP BY keyword - Syntax",
    "INSERT keyword",
    "INSERT keyword - Syntax",
    "JOIN keyword",
    "JOIN keyword - (INNER) JOIN",
    "JOIN keyword - ASOF JOIN",
    "JOIN keyword - CROSS JOIN",
    "JOIN keyword - Execution order",
    "JOIN keyword - Implicit joins",
    "JOIN keyword - LEFT (OUTER) JOIN",
    "JOIN keyword - LT JOIN",
    "JOIN keyword - SPLICE JOIN",
    "JOIN keyword - Syntax",
    "JOIN keyword - Using the `ON` clause for the `JOIN` predicate",
    "LATEST ON keyword",
    "LATEST ON keyword - Description",
    "LATEST ON keyword - Syntax",
    "LIMIT keyword",
    "LIMIT keyword - Syntax",
    "ORDER BY keyword",
    "ORDER BY keyword - Notes",
    "ORDER BY keyword - Syntax",
    "Over Keyword - Window Functions",
    "Over Keyword - Window Functions - Components of a window function",
    "Over Keyword - Window Functions - Deep Dive: What is a Window Function?",
    "Over Keyword - Window Functions - Exclusion options",
    "Over Keyword - Window Functions - Frame boundaries",
    "Over Keyword - Window Functions - Frame types and behavior",
    "Over Keyword - Window Functions - Notes and restrictions",
    "Over Keyword - Window Functions - Supported functions",
    "Over Keyword - Window Functions - Syntax",
    "Query & SQL Overview",
    "Query & SQL Overview - Apache Parquet",
    "Query & SQL Overview - PostgreSQL",
    "Query & SQL Overview - QuestDB Web Console",
    "Query & SQL Overview - REST HTTP API",
    "Query & SQL Overview - What's next?",
    "REFRESH MATERIALIZED VIEW",
    "REFRESH MATERIALIZED VIEW - See also",
    "REFRESH MATERIALIZED VIEW - Syntax",
    "REINDEX",
    "REINDEX - Options",
    "REINDEX - Syntax",
    "REMOVE USER reference",
    "REMOVE USER reference - Syntax",
    "RENAME TABLE keyword",
    "RENAME TABLE keyword - Syntax",
    "REVOKE ASSUME SERVICE ACCOUNT reference",
    "REVOKE ASSUME SERVICE ACCOUNT reference - Description",
    "REVOKE ASSUME SERVICE ACCOUNT reference - Syntax",
    "REVOKE reference",
    "REVOKE reference - Description",
    "REVOKE reference - Syntax",
    "SAMPLE BY keyword",
    "SAMPLE BY keyword - ALIGN TO CALENDAR",
    "SAMPLE BY keyword - ALIGN TO FIRST OBSERVATION",
    "SAMPLE BY keyword - FROM-TO",
    "SAMPLE BY keyword - Fill options",
    "SAMPLE BY keyword - Performance optimization",
    "SAMPLE BY keyword - Sample calculation",
    "SAMPLE BY keyword - Sample units",
    "SAMPLE BY keyword - See also",
    "SAMPLE BY keyword - Syntax",
    "SELECT keyword",
    "SELECT keyword - Additional time-series clauses",
    "SELECT keyword - Aggregation",
    "SELECT keyword - Boolean expressions",
    "SELECT keyword - Simple select",
    "SELECT keyword - Supported clauses",
    "SELECT keyword - Syntax",
    "SHOW keyword",
    "SHOW keyword - Description",
    "SHOW keyword - See also",
    "SHOW keyword - Syntax",
    "SNAPSHOT keyword",
    "SNAPSHOT keyword - Syntax",
    "TRUNCATE TABLE keyword",
    "TRUNCATE TABLE keyword - Notes",
    "TRUNCATE TABLE keyword - See also",
    "TRUNCATE TABLE keyword - Syntax",
    "UNION EXCEPT INTERSECT keywords",
    "UNION EXCEPT INTERSECT keywords - Alias",
    "UNION EXCEPT INTERSECT keywords - Clauses",
    "UNION EXCEPT INTERSECT keywords - Keyword execution priority",
    "UNION EXCEPT INTERSECT keywords - Syntax",
    "UPDATE keyword",
    "UPDATE keyword - Syntax",
    "VACUUM TABLE",
    "VACUUM TABLE - Description",
    "VACUUM TABLE - Syntax",
    "WHERE keyword",
    "WHERE keyword - Boolean",
    "WHERE keyword - Numeric",
    "WHERE keyword - Symbol and string",
    "WHERE keyword - Syntax",
    "WHERE keyword - Timestamp and date",
    "WITH keyword",
    "WITH keyword - Syntax"
  ]
}
