nodeLinker: pnp

packageExtensions:
  "@storybook/addon-interactions@*":
    dependencies:
      core-js: "*"
  "@storybook/instrumenter@*":
    dependencies:
      core-js: "*"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
