nodeLinker: pnp

packageExtensions:
  "@cypress/snapshot@*":
    dependencies:
      debug: "*"
  "@storybook/addon-interactions@*":
    dependencies:
      core-js: "*"

  "@storybook/instrumenter@*":
    dependencies:
      core-js: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
