compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@storybook/addon-interactions@*":
    dependencies:
      core-js: "*"
  "@storybook/instrumenter@*":
    dependencies:
      core-js: "*"
  "@babel/core@*":
    dependencies:
      "@babel/core": "*"

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
