checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@babel/core@*":
    dependencies:
      "@babel/core": "*"

supportedArchitectures:
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
