/**
 * The console icon system.
 *
 * Keep product iconography on one family. The aliases let existing feature
 * code keep semantic names while every rendered glyph comes from Phosphor.
 */
export {
  Plus as Add,
  ChartLineUp as AddChart,
  CaretDown as ArrowDownS,
  CaretDown as ArrowDropDown,
  ArrowLeft,
  ArrowCircleUp as ArrowUpCircle,
  CaretUp as ArrowUpS,
  BracketsCurly as Bracket,
  Broom as ResetGrid,
  BuildingOffice as Building,
  Buildings as BuildingMultiple,
  CalendarBlank as Calendar,
  CalendarMinus,
  CaretDoubleLeft as MoveColumnToFront,
  ChatCircle as Chat,
  ChatsCircle as Chat3,
  Check,
  CheckCircle,
  Circle as CheckboxBlankCircle,
  CheckCircle as CheckboxCircle,
  Check as CheckmarkOutline,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  X as Close,
  XCircle as CloseCircle,
  X as CloseOutline,
  CloudSlash as CloudOff,
  Command,
  Copy as CopyAlt,
  Database as Database2,
  Trash as DeleteBin2,
  ChatsCircle as Discourse,
  DownloadSimple as Download2,
  PencilSimple as Edit,
  EnvelopeSimple as Envelope,
  WarningCircle as Error,
  Warning as ErrorWarning,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileCode,
  Files,
  Copy as FileCopy,
  FileMagnifyingGlass as FileSearch,
  FileCsv as FiletypeCsv,
  Flask,
  MapPin as GeoAlt,
  GithubLogo as Github,
  Globe,
  Table as Grid,
  ClockCounterClockwise as History,
  Info as InfoCircle,
  Info as InfoOutline,
  Info as Information,
  RowsPlusBottom as InsertRowBottom,
  RowsPlusTop as InsertRowTop,
  ChartLine as LineChart,
  CircleNotch as Loader,
  CircleNotch as Loader3,
  CircleNotch as Loader4,
  SignOut as LogoutCircle,
  MarkdownLogo as Markdown,
  List as Menu,
  Bell as Notification2,
  HashStraight as OneHundredTwentyThree,
  Palette,
  ChartPieSlice as PieChart,
  Play,
  Question,
  ArrowClockwise as Refresh,
  ArrowCounterClockwise as Reset,
  ArrowClockwise as Restart,
  MagnifyingGlass as Search,
  MagnifyingGlass as Search2,
  SlidersHorizontal as Settings4,
  ShieldCheck,
  ShieldCheckered as ShieldLockFill,
  SlackLogo as Slack,
  SortDescending as SortDown,
  StackOverflowLogo as StackOverflow,
  Stop,
  Minus as Subtract,
  Table,
  Columns as TableFreezeColumn,
  Tag,
  UsersThree as Team,
  TerminalWindow as TerminalBox,
  Clock as Time,
  Wrench as Tools,
  Trash,
  TextT as Type,
  ArrowCounterClockwise as Undo,
  UploadSimple as Upload2,
  User,
  GlobeHemisphereWest as World,
  X,
  XSquare,
  Lightning as Zap,
} from "@phosphor-icons/react"

export type { Icon as StyledIcon } from "@phosphor-icons/react"
