export enum EventType {
  MSG_ACTIVE_SIDEBAR = "active.panel",
  MSG_EDITOR_FOCUS = "editor.focus",
  MSG_EDITOR_INSERT_COLUMN = "editor.insert.column",
  GRID_FOCUS = "grid.focus",
  MSG_CHART_DRAW = "chart.draw",
  MSG_QUERY_CANCEL = "query.in.cancel",
  MSG_QUERY_DATASET = "query.out.dataset",
  MSG_QUERY_ERROR = "query.out.error",
  MSG_QUERY_EXEC = "query.in.exec",
  MSG_QUERY_FIND_N_EXEC = "query.build.execute",
  MSG_QUERY_OK = "query.out.ok",
  MSG_QUERY_RUNNING = "query.out.running",
  MSG_QUERY_SCHEMA = "query.out.schema",
  MSG_CONNECTION_OK = "query.connection.ok",
  MSG_CONNECTION_ERROR = "query.connection.error",
  MSG_CONNECTION_UNAUTHORIZED = "query.connection.unauthorized",
  MSG_CONNECTION_FORBIDDEN = "query.connection.forbidden",
  REACT_READY = "react.ready",
  TAB_FOCUS = "tab.focus",
  TAB_BLUR = "tab.blur",
  METRICS_REFRESH_DATA = "metrics.refresh.data",
  BUFFERS_UPDATED = "buffers.updated",
}
