export enum ConsoleEvent {
  SCHEMA_OPEN = "schema.open",
  SCHEMA_CLOSE = "schema.close",
  SCHEMA_NAME_COPY = "schema.name_copy",
  SCHEMA_FILTER = "schema.filter",
  SEARCH_EXECUTE = "search.execute",
  SEARCH_OPEN = "search.open",

  EDITOR_RUN_ALL = "editor.run_all",
  EDITOR_GLYPH_RUN = "editor.glyph_run",
  EDITOR_GLYPH_CONTEXT_OPEN = "editor.glyph_context_open",
  EDITOR_GLYPH_CONTEXT_QUERY_PLAN = "editor.glyph_context_query_plan",

  GRID_CSV_DOWNLOAD = "grid.csv_download",
  GRID_PARQUET_DOWNLOAD = "grid.parquet_download",
  GRID_MARKDOWN_COPY = "grid.markdown_copy",
  GRID_REFRESH = "grid.refresh",
  GRID_LAYOUT_RESET = "grid.layout_reset",
  GRID_COLUMN_FREEZE = "grid.column_freeze",
  GRID_CELL_COPY = "grid.cell_copy",

  IMPORT_FILE_UPLOAD = "import.file_upload",
  IMPORT_ADD_SCHEMA = "import.add_schema",
  IMPORT_CHANGE_WRITE_MODE = "import.change_write_mode",
  IMPORT_SETTINGS_CHANGE = "import.settings_change",
  IMPORT_DETAILS_OPEN = "import.details_open",
  IMPORT_RESULTS_OPEN = "import.results_open",

  AI_CHAT_OPEN = "ai.chat_open",
  AI_CHAT_CLOSE = "ai.chat_close",
  AI_CHAT_SEND = "ai.chat_send",
  AI_CHAT_ACCEPT = "ai.chat_accept",
  AI_EDITOR_SUGGESTION_ACCEPT = "ai.editor.suggestion_accept",
  AI_CHAT_REJECT = "ai.chat_reject",
  AI_CHAT_DELETE = "ai.chat_delete",
  AI_CHAT_RENAME = "ai.chat_rename",
  AI_HISTORY_OPEN = "ai.history_open",
  AI_EXPLAIN_QUERY = "ai.explain_query",
  AI_FIX_QUERY = "ai.fix_query",
  AI_GLYPH_CLICK = "ai.glyph_click",
  AI_CONTEXT_BADGE_CLICK = "ai.context_badge_click",
  AI_PROVIDER_CONFIGURE = "ai.provider_configure",
  AI_CONFIGURATION_OPEN = "ai.configuration_open",
  AI_CONFIGURATION_VALIDATE = "ai.configuration_validate",
  AI_SETTINGS_OPEN = "ai.settings_open",
  AI_SETTINGS_MODEL_TOGGLE = "ai.settings_model_toggle",
  AI_SETTINGS_API_KEY_REMOVE = "ai.settings_api_key_remove",
  AI_SETTINGS_API_KEY_EDIT = "ai.settings_api_key_edit",
  AI_SETTINGS_SCHEMA_ACCESS_REMOVE = "ai.settings_schema_access_remove",
  AI_MODEL_CHANGE = "ai.model_change",

  PANEL_BOTTOM_SWITCH = "panel.bottom.switch",

  SCHEMA_FILTER_SUSPENDED = "schema.filter_suspended",
  SCHEMA_CONTEXT_MENU_OPEN = "schema.context_menu_open",
  SCHEMA_CONTEXT_RESUME_WAL = "schema.context_resume_wal",
  SCHEMA_CONTEXT_COPY_DDL = "schema.context_copy_ddl",
  SCHEMA_CONTEXT_EXPLAIN = "schema.context_explain",
  SCHEMA_COPY_MULTIPLE = "schema.copy_multiple",

  TABLE_DETAILS_OPEN = "table_details.open",
  TABLE_DETAILS_SCHEMA_EXPLAIN = "table_details.schema_explain",
  TABLE_DETAILS_ASK_AI = "table_details.ask_ai",
  TABLE_DETAILS_COPY_DDL = "table_details.copy_ddl",

  SIDEBAR_NAVIGATE = "sidebar.navigate",

  TAB_IMPORT = "tab.import",
  TAB_EXPORT = "tab.export",
  TAB_RENAME = "tab.rename",
  TAB_HISTORY_OPEN = "tab.history_open",
  TAB_HISTORY_RESTORE = "tab.history_restore",
  TAB_HISTORY_CLEAR = "tab.history_clear",

  QUERY_LOG_OPEN = "query_log.open",
  QUERY_LOG_QUERY_COPY = "query_log.query_copy",
  QUERY_LOG_CLEAR = "query_log.clear",

  METRIC_ADD = "metric.add",
  METRIC_TAB_OPEN = "metric.tab_open",

  HELP_OPEN = "help.open",
  HELP_FEEDBACK_SUBMIT = "help.feedback_submit",

  NEWS_OPEN = "news.open",
}
