export enum ConsoleEvent {
  SCHEMA_OPEN = "schema.open",
  SCHEMA_CLOSE = "schema.close",
  SCHEMA_NAME_COPY = "schema.name_copy",
  SCHEMA_FILTER = "schema.filter",
  SEARCH_EXECUTE = "search.execute",
  SEARCH_OPEN = "search.open",

  EDITOR_VIEW_TAB = "editor.view_tab",
  EDITOR_RUN_MULTIPLE = "editor.run_multiple",
  EDITOR_GLYPH_RUN = "editor.glyph_run",
  EDITOR_GLYPH_CONTEXT_OPEN = "editor.glyph_context_open",
  EDITOR_GLYPH_CONTEXT_QUERY_PLAN = "editor.glyph_context_query_plan",
  EDITOR_COPY_QUERY_LINK = "editor.copy_query_link",

  CHART_DRAW = "chart.draw",

  GRID_CSV_DOWNLOAD = "grid.csv_download",
  GRID_PARQUET_DOWNLOAD = "grid.parquet_download",
  GRID_MARKDOWN_COPY = "grid.markdown_copy",
  GRID_REFRESH = "grid.refresh",
  GRID_LAYOUT_RESET = "grid.layout_reset",
  GRID_COLUMN_FREEZE = "grid.column_freeze",
  GRID_COLUMN_MOVE_TO_FRONT = "grid.column_move_to_front",
  GRID_COLUMN_COPY = "grid.column_copy",
  GRID_CELL_COPY = "grid.cell_copy",
  GRID_SCROLL = "grid.scroll",

  IMPORT_FILE_UPLOAD = "import.file_upload",
  IMPORT_ADD_SCHEMA = "import.add_schema",
  IMPORT_CHANGE_WRITE_MODE = "import.change_write_mode",
  IMPORT_SETTINGS_CHANGE = "import.settings_change",
  IMPORT_DETAILS_OPEN = "import.details_open",
  IMPORT_RESULTS_OPEN = "import.results_open",

  AI_CHAT_OPEN = "ai.chat_open",
  AI_CHAT_CLOSE = "ai.chat_close",
  AI_CHAT_SEND = "ai.chat_send",
  AI_CHAT_ACCEPT = "ai.chat_accept",
  AI_EDITOR_SUGGESTION_ACCEPT = "ai.editor.suggestion_accept",
  AI_EDITOR_SUGGESTION_REJECT = "ai.editor.suggestion_reject",
  AI_EDITOR_SUGGESTION_APPLY = "ai.editor.suggestion_apply",
  AI_CHAT_REJECT = "ai.chat_reject",
  AI_OPEN_IN_EDITOR = "ai.open_in_editor",
  AI_CHAT_DELETE = "ai.chat_delete",
  AI_CHAT_RENAME = "ai.chat_rename",
  AI_HISTORY_OPEN = "ai.history_open",
  AI_EXPLAIN_QUERY = "ai.explain_query",
  AI_FIX_QUERY = "ai.fix_query",
  AI_GLYPH_CLICK = "ai.glyph_click",
  AI_CONTEXT_BADGE_CLICK = "ai.context_badge_click",
  AI_PROVIDER_CONFIGURE = "ai.provider_configure",
  AI_SETTINGS_PROVIDER_REMOVE = "ai.settings_provider_remove",
  AI_PROMO_OPEN = "ai.promo_open",
  AI_CONFIGURATION_OPEN = "ai.configuration_open",
  AI_CONFIGURATION_VALIDATE = "ai.configuration_validate",
  AI_SETTINGS_OPEN = "ai.settings_open",
  AI_SETTINGS_MODEL_TOGGLE = "ai.settings_model_toggle",
  AI_SETTINGS_API_KEY_EDIT = "ai.settings_api_key_edit",
  AI_SETTINGS_SCHEMA_ACCESS_REMOVE = "ai.settings_schema_access_remove",
  AI_MODEL_CHANGE = "ai.model_change",
  AI_FLOW_COMPLETE = "ai.flow_complete",

  PANEL_BOTTOM_SWITCH = "panel.bottom.switch",

  SCHEMA_FILTER_SUSPENDED = "schema.filter_suspended",
  SCHEMA_CONTEXT_MENU_OPEN = "schema.context_menu_open",
  SCHEMA_CONTEXT_RESUME_WAL = "schema.context_resume_wal",
  SCHEMA_RESUME_WAL_SUBMIT = "schema.resume_wal_submit",
  SCHEMA_CONTEXT_COPY_DDL = "schema.context_copy_ddl",
  SCHEMA_CONTEXT_EXPLAIN = "schema.context_explain",
  SCHEMA_CONTEXT_CREATE_MATVIEW = "schema.context_create_matview",
  SCHEMA_COPY_MULTIPLE = "schema.copy_multiple",

  TABLE_DETAILS_TAB_SWITCH = "table_details.tab_switch",
  TABLE_DETAILS_OPEN = "table_details.open",
  TABLE_DETAILS_SCHEMA_EXPLAIN = "table_details.schema_explain",
  TABLE_DETAILS_ASK_AI = "table_details.ask_ai",
  TABLE_DETAILS_COPY_DDL = "table_details.copy_ddl",

  SIDEBAR_NAVIGATE = "sidebar.navigate",

  TAB_ADD = "tab.add",
  TAB_ARCHIVE = "tab.archive",
  TAB_IMPORT = "tab.import",
  TAB_EXPORT = "tab.export",
  TAB_RENAME = "tab.rename",
  TAB_HISTORY_OPEN = "tab.history_open",
  TAB_HISTORY_RESTORE = "tab.history_restore",
  TAB_HISTORY_CLEAR = "tab.history_clear",

  QUERY_LOG_OPEN = "query_log.open",
  QUERY_LOG_QUERY_COPY = "query_log.query_copy",
  QUERY_LOG_CLEAR = "query_log.clear",

  METRIC_ADD = "metric.add",
  METRIC_REMOVE = "metric.remove",
  METRIC_TAB_OPEN = "metric.tab_open",
  METRIC_REFRESH_RATE_CHANGE = "metric.refresh_rate_change",

  HELP_OPEN = "help.open",
  HELP_FEEDBACK_SUBMIT = "help.feedback_submit",

  NEWS_OPEN = "news.open",

  NOTEBOOK_CREATE = "notebook.create",
  NOTEBOOK_DUPLICATE = "notebook.duplicate",
  NOTEBOOK_BUILD_WITH_AI = "notebook.build_with_ai",
  NOTEBOOK_LOAD_RETRY = "notebook.load_retry",
  NOTEBOOK_LAYOUT_MODE_CHANGE = "notebook.layout_mode_change",
  NOTEBOOK_CELL_ADD = "notebook.cell_add",
  NOTEBOOK_CELL_LIMIT_REACHED = "notebook.cell_limit_reached",
  NOTEBOOK_CELL_DELETE = "notebook.cell_delete",
  NOTEBOOK_CELL_DUPLICATE = "notebook.cell_duplicate",
  NOTEBOOK_CELL_MOVE = "notebook.cell_move",
  NOTEBOOK_CELL_RENAME = "notebook.cell_rename",
  NOTEBOOK_CELL_RUN = "notebook.cell_run",
  NOTEBOOK_CELL_DRAW = "notebook.cell_draw",
  NOTEBOOK_CELL_RUN_CANCEL = "notebook.cell_run_cancel",
  NOTEBOOK_CELL_AUTOREFRESH_CHANGE = "notebook.cell_autorefresh_change",
  NOTEBOOK_AUTOREFRESH_DEFAULT_CHANGE = "notebook.autorefresh_default_change",
  NOTEBOOK_AUTOREFRESH_RESET_OVERRIDES = "notebook.autorefresh_reset_overrides",
  NOTEBOOK_REFRESH_ALL = "notebook.refresh_all",
  NOTEBOOK_CELL_RESIZE = "notebook.cell_resize",
  NOTEBOOK_CELL_EXPAND_WIDTH = "notebook.cell_expand_width",
  NOTEBOOK_CELL_SIZE_RESET = "notebook.cell_size_reset",
  NOTEBOOK_CELL_VIEW_CHANGE = "notebook.cell_view_change",
  NOTEBOOK_CELL_VIEW_MAXIMIZE = "notebook.cell_view_maximize",
  NOTEBOOK_CELL_MAXIMIZE = "notebook.cell_maximize",
  NOTEBOOK_DRAW_TOGGLE = "notebook.draw_toggle",
  NOTEBOOK_DRAW_REFUSED = "notebook.draw_refused",
  NOTEBOOK_CHART_SETTINGS_OPEN = "notebook.chart_settings_open",
  NOTEBOOK_CHART_SETTINGS_SAVE = "notebook.chart_settings_save",
  NOTEBOOK_CHART_SETTINGS_CANCEL = "notebook.chart_settings_cancel",
  NOTEBOOK_CHART_SAVE_BLOCKED = "notebook.chart_save_blocked",
  NOTEBOOK_CHART_TYPE_CHANGE = "notebook.chart_type_change",
  NOTEBOOK_CHART_RESET_AUTO = "notebook.chart_reset_auto",
  NOTEBOOK_MARKDOWN_APPLY = "notebook.markdown_apply",
  NOTEBOOK_VARIABLES_OPEN = "notebook.variables_open",
  NOTEBOOK_VARIABLES_APPLY = "notebook.variables_apply",
  NOTEBOOK_VARIABLES_IMPORT = "notebook.variables_import",
  NOTEBOOK_RESULT_TAB_SWITCH = "notebook.result_tab_switch",
  NOTEBOOK_ONBOARDING_OPEN = "notebook.onboarding_open",
  NOTEBOOK_ONBOARDING_STEP = "notebook.onboarding_step",
  NOTEBOOK_ONBOARDING_CLOSE = "notebook.onboarding_close",

  MCP_ADD_CELL = "mcp.add_cell",
  MCP_UPDATE_CELL = "mcp.update_cell",
  MCP_DELETE_CELL = "mcp.delete_cell",
  MCP_RUN_CELL = "mcp.run_cell",
  MCP_RUN_QUERY = "mcp.run_query",
  MCP_VALIDATE_QUERY = "mcp.validate_query",
  MCP_CREATE_NOTEBOOK = "mcp.create_notebook",
  MCP_ACTIVATE_NOTEBOOK = "mcp.activate_notebook",
  MCP_DUPLICATE_NOTEBOOK = "mcp.duplicate_notebook",
  MCP_DELETE_NOTEBOOK = "mcp.delete_notebook",
  MCP_LIST_CELLS = "mcp.list_cells",
  MCP_GET_CELL = "mcp.get_cell",
  MCP_GET_NOTEBOOK_STATE = "mcp.get_notebook_state",
  MCP_MOVE_CELL_UP = "mcp.move_cell_up",
  MCP_MOVE_CELL_DOWN = "mcp.move_cell_down",
  MCP_DUPLICATE_CELL = "mcp.duplicate_cell",
  MCP_SET_LAYOUT_MODE = "mcp.set_layout_mode",
  MCP_SET_CELL_LAYOUT = "mcp.set_cell_layout",
  MCP_SET_CELL_MODE = "mcp.set_cell_mode",
  MCP_SET_CELL_CHART_CONFIG = "mcp.set_cell_chart_config",
  MCP_SET_CELL_AUTOREFRESH = "mcp.set_cell_autorefresh",
  MCP_SET_NOTEBOOK_AUTOREFRESH = "mcp.set_notebook_autorefresh",
  MCP_SET_CELL_NAME = "mcp.set_cell_name",
  MCP_SET_CELL_VIEW_MAXIMIZED = "mcp.set_cell_view_maximized",
  MCP_SET_CELL_MAXIMIZED = "mcp.set_cell_maximized",
  MCP_APPLY_NOTEBOOK_STATE = "mcp.apply_notebook_state",
  MCP_GET_TABLES = "mcp.get_tables",
  MCP_GET_TABLE_SCHEMA = "mcp.get_table_schema",
  MCP_GET_TABLE_DETAILS = "mcp.get_table_details",
  MCP_GET_QUESTDB_TOC = "mcp.get_questdb_toc",
  MCP_GET_QUESTDB_DOCUMENTATION = "mcp.get_questdb_documentation",
  MCP_GET_WORKSPACE_STATE = "mcp.get_workspace_state",
  MCP_GET_RECENT_USER_ACTIONS = "mcp.get_recent_user_actions",
  MCP_UNKNOWN_TOOL = "mcp.unknown_tool",

  MCP_PAIRING_PROMPTED = "mcp.pairing_prompted",
  MCP_PAIRING_ACCEPTED = "mcp.pairing_accepted",
  MCP_PAIRING_DECLINED = "mcp.pairing_declined",
  MCP_MANUAL_PAIR_SUBMIT = "mcp.manual_pair_submit",
  MCP_CONNECTED = "mcp.connected",
  MCP_CONNECT_FAILED = "mcp.connect_failed",
  MCP_DISCONNECTED = "mcp.disconnected",
  MCP_DISCONNECT_CLICK = "mcp.disconnect_click",
  MCP_PERMISSIONS_CHANGE = "mcp.permissions_change",

  MCP_SETUP_COMMAND_COPY = "mcp.setup_command_copy",
  MCP_AGENT_CHANGES_VIEW = "mcp.agent_changes_view",
  MCP_AGENT_CHANGES_DISMISS = "mcp.agent_changes_dismiss",
  MCP_STATUS_POPOVER_OPEN = "mcp.status_popover_open",
}
