name: Check OSS Submodule

on:
  push:

jobs:
  check_oss_submodule:
    name: Check if OSS is on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Get stuff
        run: TEST_STUFF=$(cd packages/browser-tests/questdb; git branch)

      - name: Print stuff
        run: echo $TEST_STUFF

      - name: Print name of OSS branch
        run: echo ${{ github.ref_name }}

      - name: Check OSS branch
        if: github.ref_name != 'master'
        run: exit 1
