name: Check OSS Submodule

on:
  push:

jobs:
  check_oss_submodule:
    name: Check if OSS is on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Check OSS branch
        run: |
          uv run --with "pygit2==1.14.1" submodule_is_mergeable.py
