name: Check OSS Submodule

on:
  push:

jobs:
  check_oss_submodule:
    name: Check if OSS is on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

#      - name: Get current prefix
#        id: branch-prefix
#        run: |
#          prefix=$(echo `git branch`)
#          echo "::set-output name=prefix::$prefix"

#      - name: Stuff
#        run: |
#          TEST_STUFF=$(cd packages/browser-tests/questdb; git branch)
#          if: ${{ ! startsWith($TEST_STUFF, 'refs/tags/') }}

#      - name: Print name of OSS branch
#        run: echo ${{ steps.branch-prefix.output.prefix }}

#      - name: Check OSS branch
#        if: ${{ steps.branch-prefix.output.prefix != 'master' }}
#        run: exit 1

#      - name: Check OSS branch
#        run: ./oss_master_check.sh

      - name: Check OSS branch
        run: |
          python3 -m pip install -U pip
          python3 -m pip install --upgrade pygit2==1.14.1
          python3 submodule_is_mergeable.py
