name: Check OSS Submodule

on:
  push:

jobs:
  check_oss_submodule:
    name: Check if OSS is on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Check OSS branch
        run: echo ${{ github.ref_name }}
